"use strict";
const fs=require("node:fs"), path=require("node:path"), os=require("node:os"), zlib=require("node:zlib");
const {spawn}=require("node:child_process");
function loadEnv(){try{for(const l of fs.readFileSync(path.join(__dirname,".env"),"utf8").split(/\r?\n/)){const m=l.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/);if(!m||l.trim().startsWith("#")||process.env[m[1]]!==undefined)continue;let v=m[2];if((v[0]==='"'&&v.endsWith('"'))||(v[0]==="'"&&v.endsWith("'")))v=v.slice(1,-1);process.env[m[1]]=v;}}catch(e){if(e.code!=="ENOENT")throw e;}}
loadEnv();
const TOKEN=String(process.env.TELEGRAM_BOT_TOKEN||"").trim(), OWNER=String(process.env.TELEGRAM_OWNER_ID||"").trim(), BASE=String(process.env.MCE_URL||"http://127.0.0.1:3010").replace(/\/+$/,"");
const sessions=new Map();let offset=0,stopping=false;
function check(){if(!TOKEN)throw Error("TELEGRAM_BOT_TOKEN belum diatur.");if(!/^\d+$/.test(OWNER))throw Error("TELEGRAM_OWNER_ID harus berupa angka.");if(!["127.0.0.1","localhost","::1"].includes(new URL(BASE).hostname))throw Error("MCE_URL wajib localhost.");}
function sess(id){if(!sessions.has(id))sessions.set(id,{messages:[],pending:null,staged:null});return sessions.get(id);}
function errorText(e){return String(e&&e.message||e).replaceAll(TOKEN,"[REDACTED]").slice(0,1000);}
async function api(method,route,body){const r=await fetch(new URL(route,BASE),{method,headers:body===undefined?{}:{"content-type":"application/json"},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(120000)});const t=await r.text();let d;try{d=JSON.parse(t)}catch{d={text:t}}if(!r.ok)throw Error(d.error||d.text||("API HTTP "+r.status));return d;}
async function tg(method,data){const r=await fetch("https://api.telegram.org/bot"+TOKEN+"/"+method,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data),signal:AbortSignal.timeout(65000)});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw Error(d.description||("Telegram HTTP "+r.status));return d.result;}
async function say(chat,text){for(const part of (String(text||"(kosong)").match(/[\s\S]{1,3900}/g)||["(kosong)"]))await tg("sendMessage",{chat_id:chat,text:part});}
const help=()=> "Mobile Code v6 bot\n/status — status server/workspace/provider\n/models — daftar koneksi/model\n/files [filter] — daftar file\n/read <path> — baca teks\n/write <path> — siapkan tulis file; wajib /confirmwrite\n/confirmwrite — simpan setelah pratinjau\n/cancel — batalkan operasi tertunda\n/chat <instruksi> — AI coding; teks biasa juga ke AI\n/new — reset konteks AI\n/zip — buat dan kirim ZIP nyata\n/git status | /git push — status/push normal tanpa force\n/run git-status | git-log | npm-test | npm-build | node-check <file>\n/help — bantuan\nHanya pemilik di private chat. Jangan kirim rahasia lewat Telegram.";
function flatten(nodes,out=[]){for(const n of Array.isArray(nodes)?nodes:[]){out.push((n.type==="directory"?"DIR ":"FILE ")+n.path);if(n.type==="directory")flatten(n.children,out);}return out;}
async function status(chat){const r=await Promise.all([api("GET","/api/info"),api("GET","/api/workspace"),api("GET","/api/connections")]);await say(chat,"Mobile Code API: OK\nOS: "+(r[0].platform||os.platform())+" · Node "+(r[0].node||process.version)+"\nWorkspace: "+(r[1].path||r[0].workspace||"?")+"\nProvider: "+r[2].length+(r[2].length?"\n"+r[2].map(c=>"• "+c.name+" — "+(c.model||"default")).join("\n"):"")+"\nURL: "+BASE);}
async function models(chat){const cs=await api("GET","/api/connections");if(!cs.length)return say(chat,"Belum ada provider; tambahkan di Developer Hub → Connections.");const out=[];for(const c of cs){let m=[];try{m=(await api("GET","/api/ai/models?connectionId="+encodeURIComponent(c.id))).models||[]}catch(e){m=[errorText(e)]}out.push(c.name+" — "+(c.model||"default")+"\n"+c.baseUrl+"\n"+m.slice(0,25).join(", "));}await say(chat,out.join("\n\n"));}
function crc32(b){let c=0xffffffff;for(const x of b){c^=x;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function makeZip(root){const excluded=new Set([".git",".mce","node_modules",".next",".cache","coverage",".venv","venv","dist","build"]);const files=[];function walk(dir,rel){for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(excluded.has(e.name)||e.name===".env"||e.name.startsWith(".env.")||e.name.endsWith(".zip")||e.name.endsWith(".log")||/\.(pem|key|p12|pfx|sqlite|db)$/i.test(e.name))continue;const f=path.join(dir,e.name),n=path.join(rel,e.name).replaceAll("\\","/");if(e.isDirectory())walk(f,n);else if(e.isFile())files.push({name:n,data:fs.readFileSync(f),date:fs.statSync(f).mtime});}}walk(root,"");const local=[],central=[];let off=0;for(const f of files){const n=Buffer.from(f.name),d=zlib.deflateRawSync(f.data),crc=crc32(f.data),dt=f.date,t=(dt.getHours()<<11)|(dt.getMinutes()<<5)|Math.floor(dt.getSeconds()/2),da=((Math.max(1980,dt.getFullYear())-1980)<<9)|((dt.getMonth()+1)<<5)|dt.getDate();if(f.data.length>0xffffffff||d.length>0xffffffff||off>0xffffffff)throw Error("ZIP64 belum didukung.");const h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50,0);h.writeUInt16LE(20,4);h.writeUInt16LE(0x0800,6);h.writeUInt16LE(8,8);h.writeUInt16LE(t,10);h.writeUInt16LE(da,12);h.writeUInt32LE(crc,14);h.writeUInt32LE(d.length,18);h.writeUInt32LE(f.data.length,22);h.writeUInt16LE(n.length,26);h.writeUInt16LE(0,28);local.push(h,n,d);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50,0);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(0x0800,8);c.writeUInt16LE(8,10);c.writeUInt16LE(t,12);c.writeUInt16LE(da,14);c.writeUInt32LE(crc,16);c.writeUInt32LE(d.length,20);c.writeUInt32LE(f.data.length,24);c.writeUInt16LE(n.length,28);c.writeUInt16LE(0,30);c.writeUInt16LE(0,32);c.writeUInt16LE(0,34);c.writeUInt16LE(0,36);c.writeUInt32LE(0,38);c.writeUInt32LE(off,42);central.push(c,n);off+=h.length+n.length+d.length;}const size=central.reduce((a,b)=>a+b.length,0),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(0,4);end.writeUInt16LE(0,6);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(size,12);end.writeUInt32LE(off,16);end.writeUInt16LE(0,20);return{buffer:Buffer.concat([...local,...central,end]),count:files.length};}
async function upload(chat,bytes,name,caption){if(bytes.length>45*1024*1024)throw Error("ZIP lebih dari 45 MB.");const f=new FormData();f.append("chat_id",String(chat));f.append("caption",caption.slice(0,900));f.append("document",new Blob([bytes]),name);const r=await fetch("https://api.telegram.org/bot"+TOKEN+"/sendDocument",{method:"POST",body:f,signal:AbortSignal.timeout(120000)});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw Error(d.description||"Upload Telegram gagal.");}
async function ai(chat,prompt){const s=sess(chat),cs=await api("GET","/api/connections");if(!cs.length)throw Error("Provider belum dikonfigurasi di Connections.");const messages=s.messages.concat([{role:"user",content:prompt}]).slice(-16);await say(chat,"⏳ AI sedang bekerja di workspace…");const d=await api("POST","/api/ai/chat",{connectionId:cs[0].id,model:"",messages});const answer=String(d.text||"AI selesai tanpa teks.");s.messages=s.messages.concat([{role:"user",content:prompt},{role:"assistant",content:answer}]).slice(-16);let meta=[];if(d.model)meta.push("Model: "+d.model);if(d.usage)meta.push("Token masuk: "+(d.usage.prompt_tokens??"—")+" · keluar: "+(d.usage.completion_tokens??"—"));if(d.changes&&d.changes.length)meta.push("File berubah: "+d.changes.map(x=>x.path).slice(0,10).join(", "));await say(chat,answer+(meta.length?"\n\n"+meta.join("\n"):""));for(const a of d.artifacts||[]){if(!a.url)continue;try{const u=new URL(a.url,BASE),b=new URL(BASE);if(u.hostname!==b.hostname||u.port!==b.port)continue;const r=await fetch(u);if(r.ok){const bytes=Buffer.from(await r.arrayBuffer());if(bytes.length)await upload(chat,bytes,a.filename||"artifact.zip","Artefak Mobile Code");}}catch(e){await say(chat,"Artefak tidak terkirim: "+errorText(e));}}}
function runAllowed(action,cwd){return new Promise((resolve,reject)=>{let cmd,args;if(action==="git-status"){cmd="git";args=["status","--short","--branch"];}else if(action==="git-log"){cmd="git";args=["log","-5","--oneline"];}else if(action==="npm-test"){cmd="npm";args=["test","--if-present"];}else if(action==="npm-build"){cmd="npm";args=["run","build","--if-present"];}else if(action.startsWith("node-check ")){const rel=action.slice(11).trim();if(!rel||path.isAbsolute(rel)||rel.split(/[\\/]+/).includes(".."))return reject(Error("Path harus relatif di workspace."));const target=path.resolve(cwd,rel);if(!target.startsWith(path.resolve(cwd)+path.sep))return reject(Error("Path di luar workspace."));cmd=process.execPath;args=["--check",target];}else return reject(Error("Aksi tidak diizinkan; lihat /help."));const p=spawn(cmd,args,{cwd,shell:false,windowsHide:true,env:process.env});let out="";const collect=b=>{out+=b.toString();if(out.length>10000)out=out.slice(-10000)};p.stdout.on("data",collect);p.stderr.on("data",collect);const timer=setTimeout(()=>{p.kill();reject(Error("Timeout 60 detik."));},60000);p.on("error",e=>{clearTimeout(timer);reject(e)});p.on("close",code=>{clearTimeout(timer);resolve("Exit code: "+code+"\n"+(out||"(tanpa output)"));});});}
async function git(chat,action){const w=await api("GET","/api/workspace");if(action==="status")return say(chat,await runAllowed("git-status",w.path));if(action!=="push")throw Error("Gunakan /git status atau /git push.");await say(chat,"Menjalankan git push normal ke remote tersimpan, tanpa force.");const result=await new Promise((resolve,reject)=>{const p=spawn("git",["push"],{cwd:w.path,shell:false,windowsHide:true,env:process.env});let out="";const collect=b=>{out+=b.toString();if(out.length>9000)out=out.slice(-9000)};p.stdout.on("data",collect);p.stderr.on("data",collect);const timer=setTimeout(()=>{p.kill();reject(Error("git push timeout 90 detik."));},90000);p.on("error",e=>{clearTimeout(timer);reject(e)});p.on("close",c=>{clearTimeout(timer);resolve("Exit code: "+c+"\n"+(out||"(tanpa output)"));});});await say(chat,result);}
function validPath(p){return !!p&&!path.isAbsolute(p)&&!p.split(/[\\/]+/).includes("..");}
async function handle(m){const chat=m.chat&&m.chat.id;if(String(m.from&&m.from.id||"")!==OWNER||!m.chat||m.chat.type!=="private"){if(chat&&m.chat&&m.chat.type==="private")try{await tg("sendMessage",{chat_id:chat,text:"Akses ditolak."})}catch{}return;}if(typeof m.text!=="string")return;const text=m.text.trim(),s=sess(chat);if(!text)return;
if(s.pending){if(text==="/cancel"){s.pending=null;return say(chat,"Penulisan dibatalkan.");}if(text.startsWith("/"))return say(chat,"Kirim isi file biasa atau /cancel.");s.staged={path:s.pending,content:text};s.pending=null;return say(chat,"Pratinjau "+s.staged.path+" ("+Buffer.byteLength(text)+" byte). Belum disimpan. Kirim /confirmwrite atau /cancel.");}
if(text==="/start"||text==="/help")return say(chat,help());if(text==="/status")return status(chat);if(text==="/models")return models(chat);if(text==="/new"){s.messages=[];s.staged=null;return say(chat,"Konteks AI direset.");}if(text==="/cancel"){s.pending=null;s.staged=null;return say(chat,"Operasi tertunda dibatalkan.");}
if(text==="/confirmwrite"){if(!s.staged)return say(chat,"Tidak ada file menunggu konfirmasi.");const f=s.staged;await api("PUT","/api/file",{path:f.path,content:f.content});s.staged=null;return say(chat,"File tersimpan: "+f.path);}
if(text.startsWith("/write ")){const p=text.slice(7).trim();if(!validPath(p))throw Error("Path harus relatif di workspace.");s.pending=p;s.staged=null;return say(chat,"Kirim isi file pada pesan berikutnya. Tidak disimpan sebelum /confirmwrite.");}
if(text.startsWith("/read ")){const p=text.slice(6).trim();if(!validPath(p))throw Error("Path harus relatif di workspace.");const d=await api("GET","/api/file?path="+encodeURIComponent(p));return say(chat,"FILE "+p+"\n\n"+(typeof d.text==="string"?d.text:JSON.stringify(d)));}
if(text.startsWith("/files")){const f=text.slice(6).trim().toLowerCase(),tree=await api("GET","/api/tree");return say(chat,flatten(tree).filter(x=>!f||x.toLowerCase().includes(f)).slice(0,180).join("\n")||"Tidak ada file cocok.");}
if(text==="/zip"){const w=await api("GET","/api/workspace"),z=makeZip(w.path);await upload(chat,z.buffer,"mobile-code-workspace.zip","ZIP "+z.count+" file; rahasia, .mce, .git, node_modules dan cache dikecualikan.");return say(chat,"ZIP nyata berhasil dikirim ("+z.count+" file).");}
if(text.startsWith("/git"))return git(chat,text.slice(4).trim()||"status");if(text.startsWith("/run ")){const w=await api("GET","/api/workspace");return say(chat,await runAllowed(text.slice(5).trim(),w.path));}if(text.startsWith("/chat "))return ai(chat,text.slice(6).trim());if(text.startsWith("/"))return say(chat,"Perintah tidak dikenal. Kirim /help.");return ai(chat,text);}
async function main(){check();console.log("Mobile Code Telegram long polling; API "+BASE);const me=await tg("getMe",{});console.log("Bot authenticated: @"+me.username);while(!stopping){try{const updates=await tg("getUpdates",{offset,timeout:30,allowed_updates:["message"]});for(const u of updates){offset=Math.max(offset,Number(u.update_id)+1);if(!u.message)continue;try{await handle(u.message)}catch(e){console.error("Update error:",errorText(e));if(String(u.message.from&&u.message.from.id||"")===OWNER&&u.message.chat)try{await say(u.message.chat.id,"Error: "+errorText(e))}catch{}}}}catch(e){console.error("Polling error:",errorText(e));await new Promise(r=>setTimeout(r,2500));}}}
process.on("SIGINT",()=>{stopping=true;process.exit(0)});process.on("SIGTERM",()=>{stopping=true;process.exit(0)});main().catch(e=>{console.error(errorText(e));process.exit(1)});
